import Head from "next/head";
import Image from "next/image";
import Contact from "../components/Contact";
import Experiance from "../components/Experiance";
import Introduction from "../components/Introduction";
import Navbar from "../components/Navbar";
import Portfolio from "../components/Portfolio";
import Services from "../components/Services";
import styles from "../styles/Home.module.css";
import { getProjects, getTeches } from "../services";
import Footer from "../components/Footer";
import About from "../components/About";

export default function Home({ projects, teches }) {
  console.log(projects);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Introduction />
        <About />
        <Services />
        <Portfolio
          projects={projects.projectsConnection.edges}
          teches={teches}
        />
        <Experiance />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const projects = (await getProjects()) || [];
  const teches = await getTeches();
  console.log({ projects });
  return {
    props: { projects, teches },
  };
}
