import React from "react";
import Navbar from "../../components/Navbar";
import styles from "../../styles/Project.module.css";
import Head from "next/head";
import Project from "../../components/Project";
import Comments from "../../components/Comments";
import { getProject } from "../../services";


const ProjectDetails = ({ project }) => {
  console.log(project.comments);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar />
        <Project project={project} />
        {/* <Comments comments={project.comment} /> */}
      </div>
    </div>
  );
};

export default ProjectDetails;

export async function getServerSideProps(context) {
  const { params } = context;
  const { id } = params;
  const project = (await getProject(id)) || {};

  return {
    props: { project: project.project },
  };
}
